services:
  spot-ros2-driver:
    image: spot_ros2:latest
    volumes:
      - ./spot_driver/config/spot_ros_example.yaml:/ros_ws/src/robot.yaml
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash && 
        source /ros_ws/install/setup.bash && 
        ros2 launch spot_driver spot_driver.launch.py config_file:=/ros_ws/src/robot.yaml spot_name:=timon launch_rviz:=False
      "
