/**:
  ros__parameters:
    command_rate: 50.0
    seconds_per_motion: 2.0

    stand_joint_angles: [0.12, 0.72, -1.45, -0.12, 0.72, -1.45, 0.12, 0.72, -1.45, -0.12, 0.72, -1.45]
    squat_joint_angles: [0.15, 1.30, -2.25, -0.15, 1.30, -2.25, 0.15, 1.30, -2.25, -0.15, 1.30, -2.25]

    joints_to_wiggle:    [16,   18  ]
    wiggle_up_offsets:   [ 1.0, -0.5]
    wiggle_down_offsets: [-1.0, -0.5]
