name: Test spot_ros2
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bdaiinstitute/bdaii_ros2_humble:main
    steps:
    - name: Build and run tests
      working-directory: spot_driver
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install
