name: spot_ros2 CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  build_package_&_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/bdaiinstitute/spot_ros2_jammy_humble:main
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        pwd 
        apt-get update
        apt install wget 
        ./install_spot_ros2.sh
        # go to root folder
        cd ../../
        colcon build --symlink-install
        source install/local_setup.bash
    - name: Install docs dependencies & build docs
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        # go to documentation folder and build the .rst files 
        cd docs
        # we don't use the --implicit-namespaces flag
        sphinx-apidoc -f -o source/ ../ ../*setup* ../examples ../*launch.py ../*command_spot_driver.py
        cd ..
        sphinx-build docs _build -v
